version: 0.2

phases:
  build:
    commands:
      - pwd
      - ls -l
      - ./gradlew build
      - ls -l
      - ls -l build/libs

artifacts:
  files:
    - build/libs/tubers.web-0.0.1-SNAPSHOT.jar
  discard-paths: yes
